### ISSUE TITLE
A ton of parser/phx/document.parser errors since server upgrade

### ISSUE THREAD

**Issue by soydemadrid** [modxcms/evolution#717]
Hi I have a site that won't load up since upgrading my server to mysql 5.7 and php7. The backend/manager works fine, but the website or homepage itself is a blank white page. I get the following errors in my apache log:

```
PHP Fatal error:  Uncaught Error: Call to undefined function mysql_result() in /home/public_html/manager/includes/document.parser.class.inc.php(1120) : eval()'d code:27, referer: http://www.fortheloveofcars.com/manager/index.php?a=1&f=menu
Stack trace:, referer: http://www.fortheloveofcars.com/manager/index.php?a=1&f=menu
#0 /home/public_html/manager/includes/document.parser.class.inc.php(1120): eval(), referer: http://www.fortheloveofcars.com/manager/index.php?a=1&f=menu
#1 /home/public_html/manager/includes/document.parser.class.inc.php(1195): DocumentParser->evalSnippet('/*\\r\\nEasy Newsle...', Array), referer: http://www.fortheloveofcars.com/manager/index.php?a=1&f=menu
#2 /home/public_html/manager/includes/document.parser.class.inc.php(1172): DocumentParser->_get_snip_result('easy newsletter'), referer: http://www.fortheloveofcars.com/manager/index.php?a=1&f=menu
#3 /home/public_html/assets/plugins/phx/phx.parser.class.inc.php(131): DocumentParser->evalSnippets('[[easy newslett...'), referer: http://www.fortheloveofcars.com/manager/index.php?a=1&f=menu
#4 /home/public_html/assets/plugins/phx/phx.parser.class.inc.php(64): PHxParser->ParseValues('<!DOCTYPE html ...'), referer: http://www.fortheloveofcars.com/manager/index.php?a=1&f=menu
#5 /home/public_html/assets/plugins/phx/phx.parser.class.inc.php(49): PHxParser->Parse('{{cnk.Header}}\\r...'), referer: http://www.fortheloveofcars.com/manager/index.php?a=1&f=menu
#6 /home/public_html/manager/inclu in /home/public_html/manager/includes/document.parser.class.inc.php(1120) : eval()'d code on line 27, referer: http://www.fortheloveofcars.com/manager/index.php?a=1&f=menu
```

If anyone could please help with a way to fix this? Any help much appreciated. :)

**Comment by Deesen** [comment]
But these errors seem related to manager-menu and do not show what is going wrong on your frontend.

**Comment by soydemadrid** [comment]
Deleted the dodgy snippet and module "Easy Newsletter 0.3" from the manager and now the site works great. Thanks!

**Comment by soydemadrid** [comment]
Hi I just received a system notification email warning of further errors so we're not quite fixed yet. This time when I login and check it looks like I can't edit any resources?

```
« MODX Parse Error »
Execution of a query to the database failed - Expression #1 of ORDER BY clause is not in SELECT list, references column 'bobrayisthebest.tvtpl.rank' which is not in SELECT list; this is incompatible with DISTINCT
SQL > SELECT DISTINCT tv.*, IF(tvc.value!='',tvc.value,tv.default_text) as value FROM `bobrayisthebest`.`modx_site_tmplvars` AS tv INNER JOIN `bobrayisthebest`.`modx_site_tmplvar_templates` AS tvtpl ON tvtpl.tmplvarid = tv.id LEFT JOIN `bobrayisthebest`.`modx_site_tmplvar_contentvalues` AS tvc ON tvc.tmplvarid=tv.id AND tvc.contentid='6' LEFT JOIN `bobrayisthebest`.`modx_site_tmplvar_access` AS tva ON tva.tmplvarid=tv.id WHERE tvtpl.templateid='9' AND (1='1' OR ISNULL(tva.documentgroup)) ORDER BY tvtpl.rank,tv.rank, tv.id 
```

and

```
include_once(string $var1)
manager/index.php on line 305
DBAPI->select(string $var1, string $var2, string $var3, string $var4)
manager/actions/mutate_content.dynamic.php on line 753
DBAPI->query(string $var1)
manager/includes/extenders/dbapi.mysqli.class.inc.php on line 146
```

Thanks again for any fixes :)

**Comment by Deesen** [comment]
Check https://github.com/modxcms/evolution/commit/a374a3f53761186aff1e3905334f5498884d65fa

**Comment by soydemadrid** [comment]
That fix is just awesome!
